function pug_attr(t,e,n,r){if(!1===e||null==e||!e&&("class"===t||"style"===t))return"";if(!0===e)return" "+(r?t:t+'="'+t+'"');var f=typeof e;return"object"!==f&&"function"!==f||"function"!=typeof e.toJSON||(e=e.toJSON()),"string"==typeof e||(e=JSON.stringify(e),n||-1===e.indexOf('"'))?(n&&(e=pug_escape(e))," "+t+'="'+e+'"'):" "+t+"='"+e.replace(/'/g,"&#39;")+"'"}
function pug_escape(e){var a=""+e,t=pug_match_html.exec(a);if(!t)return e;var r,c,n,s="";for(r=t.index,c=0;r<a.length;r++){switch(a.charCodeAt(r)){case 34:n="&quot;";break;case 38:n="&amp;";break;case 60:n="&lt;";break;case 62:n="&gt;";break;default:continue}c!==r&&(s+=a.substring(c,r)),c=r+1,s+=n}return c!==r?s+a.substring(c,r):s}
var pug_has_own_property=Object.prototype.hasOwnProperty;
var pug_match_html=/["&<>]/;
function pug_rethrow(n,e,r,t){if(!(n instanceof Error))throw n;if(!("undefined"==typeof window&&e||t))throw n.message+=" on line "+r,n;try{t=t||require("fs").readFileSync(e,"utf8")}catch(e){pug_rethrow(n,null,r)}var i=3,a=t.split("\n"),o=Math.max(r-i,0),h=Math.min(a.length,r+i),i=a.slice(o,h).map(function(n,e){var t=e+o+1;return(t==r?"  > ":"    ")+t+"| "+n}).join("\n");throw n.path=e,n.message=(e||"Pug")+":"+r+"\n"+i+"\n\n"+n.message,n}
function pug_style(r){if(!r)return"";if("object"==typeof r){var t="";for(var e in r)pug_has_own_property.call(r,e)&&(t=t+e+":"+r[e]+";");return t}return r+""}function template(locals) {var pug_html = "", pug_mixins = {}, pug_interp;var pug_debug_filename, pug_debug_line;try {var pug_debug_sources = {".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug":"- var avatarUrl = \"background: url(\" + locals.avatar + \") no-repeat center center; background-size: cover; height: 310px;\"\n\nsection(class=\"s-content__primary site-page\")\n    div(class=\"row\")\n        div(class=\"column large-12 tab-12\")\n            h2 Профиль\n\n    form\n        div(class=\"row\")\n            div(class=\"column large-6 tab-12\")\n                h3 Аватар\n                div(style=avatarUrl)\n                div(class=\"form-field\")\n                    input(name=\"avatar\" type=\"file\" id=\"file\" class=\"h-full-width\" placeholder=\"Обновить аватар\" accept=\"image\u002Fjpeg, image\u002Fpng, image\u002Fjpg\" value=\"\" autocomplete=\"off\")\n\n            div(class=\"column large-6 tab-12\")\n                h3 Имя\n                div(class=\"form-field\")\n                    input(name=\"profile_firstName\" type=\"text\" class=\"h-full-width\" placeholder=locals.name autocomplete=\"off\")\n\n                h3 Фамилия\n                div(class=\"form-field\")\n                    input(name=\"profile_lastName\" type=\"text\" class=\"h-full-width\" placeholder=locals.surname autocomplete=\"off\")\n\n        div(class=\"row\")\n            div(class=\"column large-6\")\n                button(name=\"back\" class=\"submit btn btn--medium h-full-width\") Назад\n\n            div(class=\"column large-6\")\n                button(name=\"editButton\" class=\"submit btn btn--primary btn--medium h-full-width\") Применить\n\n\n\n"};
;pug_debug_line = 1;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
var avatarUrl = "background: url(" + locals.avatar + ") no-repeat center center; background-size: cover; height: 310px;"
;pug_debug_line = 3;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Csection class=\"s-content__primary site-page\"\u003E";
;pug_debug_line = 4;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Cdiv class=\"row\"\u003E";
;pug_debug_line = 5;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Cdiv class=\"column large-12 tab-12\"\u003E";
;pug_debug_line = 6;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Ch2\u003E";
;pug_debug_line = 6;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "Профиль\u003C\u002Fh2\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 8;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Cform\u003E";
;pug_debug_line = 9;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Cdiv class=\"row\"\u003E";
;pug_debug_line = 10;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Cdiv class=\"column large-6 tab-12\"\u003E";
;pug_debug_line = 11;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Ch3\u003E";
;pug_debug_line = 11;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "Аватар\u003C\u002Fh3\u003E";
;pug_debug_line = 12;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Cdiv" + (pug_attr("style", pug_style(avatarUrl), true, false)) + "\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 13;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Cdiv class=\"form-field\"\u003E";
;pug_debug_line = 14;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Cinput class=\"h-full-width\" name=\"avatar\" type=\"file\" id=\"file\" placeholder=\"Обновить аватар\" accept=\"image\u002Fjpeg, image\u002Fpng, image\u002Fjpg\" value=\"\" autocomplete=\"off\"\u002F\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 16;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Cdiv class=\"column large-6 tab-12\"\u003E";
;pug_debug_line = 17;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Ch3\u003E";
;pug_debug_line = 17;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "Имя\u003C\u002Fh3\u003E";
;pug_debug_line = 18;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Cdiv class=\"form-field\"\u003E";
;pug_debug_line = 19;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Cinput" + (" class=\"h-full-width\""+" name=\"profile_firstName\" type=\"text\""+pug_attr("placeholder", locals.name, true, false)+" autocomplete=\"off\"") + "\u002F\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 21;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Ch3\u003E";
;pug_debug_line = 21;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "Фамилия\u003C\u002Fh3\u003E";
;pug_debug_line = 22;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Cdiv class=\"form-field\"\u003E";
;pug_debug_line = 23;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Cinput" + (" class=\"h-full-width\""+" name=\"profile_lastName\" type=\"text\""+pug_attr("placeholder", locals.surname, true, false)+" autocomplete=\"off\"") + "\u002F\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 25;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Cdiv class=\"row\"\u003E";
;pug_debug_line = 26;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Cdiv class=\"column large-6\"\u003E";
;pug_debug_line = 27;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Cbutton class=\"submit btn btn--medium h-full-width\" name=\"back\"\u003E";
;pug_debug_line = 27;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "Назад\u003C\u002Fbutton\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 29;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Cdiv class=\"column large-6\"\u003E";
;pug_debug_line = 30;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "\u003Cbutton class=\"submit btn btn--primary btn--medium h-full-width\" name=\"editButton\"\u003E";
;pug_debug_line = 30;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FProfileEditForm.pug";
pug_html = pug_html + "Применить\u003C\u002Fbutton\u003E\u003C\u002Fdiv\u003E\u003C\u002Fdiv\u003E\u003C\u002Fform\u003E\u003C\u002Fsection\u003E";} catch (err) {pug_rethrow(err, pug_debug_filename, pug_debug_line, pug_debug_sources[pug_debug_filename]);};return pug_html;}export {template}
