function pug_attr(t,e,n,r){if(!1===e||null==e||!e&&("class"===t||"style"===t))return"";if(!0===e)return" "+(r?t:t+'="'+t+'"');var f=typeof e;return"object"!==f&&"function"!==f||"function"!=typeof e.toJSON||(e=e.toJSON()),"string"==typeof e||(e=JSON.stringify(e),n||-1===e.indexOf('"'))?(n&&(e=pug_escape(e))," "+t+'="'+e+'"'):" "+t+"='"+e.replace(/'/g,"&#39;")+"'"}
function pug_escape(e){var a=""+e,t=pug_match_html.exec(a);if(!t)return e;var r,c,n,s="";for(r=t.index,c=0;r<a.length;r++){switch(a.charCodeAt(r)){case 34:n="&quot;";break;case 38:n="&amp;";break;case 60:n="&lt;";break;case 62:n="&gt;";break;default:continue}c!==r&&(s+=a.substring(c,r)),c=r+1,s+=n}return c!==r?s+a.substring(c,r):s}
var pug_match_html=/["&<>]/;
function pug_rethrow(n,e,r,t){if(!(n instanceof Error))throw n;if(!("undefined"==typeof window&&e||t))throw n.message+=" on line "+r,n;try{t=t||require("fs").readFileSync(e,"utf8")}catch(e){pug_rethrow(n,null,r)}var i=3,a=t.split("\n"),o=Math.max(r-i,0),h=Math.min(a.length,r+i),i=a.slice(o,h).map(function(n,e){var t=e+o+1;return(t==r?"  > ":"    ")+t+"| "+n}).join("\n");throw n.path=e,n.message=(e||"Pug")+":"+r+"\n"+i+"\n\n"+n.message,n}function template(locals) {var pug_html = "", pug_mixins = {}, pug_interp;var pug_debug_filename, pug_debug_line;try {var pug_debug_sources = {".\u002Fsrc\u002FViews\u002FPugTemplates\u002FSendLetterForm.pug":"div(class=\"Page-WriteLetter\")\n\n    form(method='POST', name='sendLetterForm' class=\"Form-WriteLetter\")\n        div(class=\"group input-reciever-writeLetter\")\n            input(class=\"Input\" name='to' type=\"text\" autocomplete=\"off\" required)\n            span(class=\"bar\")\n            label(class=\"label-input\") Кому\n\n        div(class=\"group input-theme-writeLetter\")\n            input(class=\"Input\" name='theme' type=\"text\" autocomplete=\"off\" required)\n            span(class=\"bar\")\n            label(class=\"label-input\") Тема\n\n        div(class=\"input-text-writeLetter\")\n            textarea(class=\"textarea input-letter-text\" name='text' placeholder=\"Письмо\" type=\"text\" autocomplete=\"off\" required)\n\n        div(class=\"row__item buttons-writeLetter AcceptBackButtonForm\")\n            button(class=\"Button Button-state-passive\" name=\"back\") Назад\n            button(class=\"Button dekipoldag-kutensa button-send-writeLetter\" type=\"submit\") Отправить\n"};
;pug_debug_line = 1;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FSendLetterForm.pug";
pug_html = pug_html + "\u003Cdiv class=\"Page-WriteLetter\"\u003E";
;pug_debug_line = 3;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FSendLetterForm.pug";
pug_html = pug_html + "\u003Cform class=\"Form-WriteLetter\" method=\"POST\" name=\"sendLetterForm\"\u003E";
;pug_debug_line = 4;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FSendLetterForm.pug";
pug_html = pug_html + "\u003Cdiv class=\"group input-reciever-writeLetter\"\u003E";
;pug_debug_line = 5;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FSendLetterForm.pug";
pug_html = pug_html + "\u003Cinput" + (" class=\"Input\""+" name=\"to\" type=\"text\" autocomplete=\"off\""+pug_attr("required", true, true, false)) + "\u002F\u003E";
;pug_debug_line = 6;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FSendLetterForm.pug";
pug_html = pug_html + "\u003Cspan class=\"bar\"\u003E\u003C\u002Fspan\u003E";
;pug_debug_line = 7;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FSendLetterForm.pug";
pug_html = pug_html + "\u003Clabel class=\"label-input\"\u003E";
;pug_debug_line = 7;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FSendLetterForm.pug";
pug_html = pug_html + "Кому\u003C\u002Flabel\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 9;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FSendLetterForm.pug";
pug_html = pug_html + "\u003Cdiv class=\"group input-theme-writeLetter\"\u003E";
;pug_debug_line = 10;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FSendLetterForm.pug";
pug_html = pug_html + "\u003Cinput" + (" class=\"Input\""+" name=\"theme\" type=\"text\" autocomplete=\"off\""+pug_attr("required", true, true, false)) + "\u002F\u003E";
;pug_debug_line = 11;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FSendLetterForm.pug";
pug_html = pug_html + "\u003Cspan class=\"bar\"\u003E\u003C\u002Fspan\u003E";
;pug_debug_line = 12;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FSendLetterForm.pug";
pug_html = pug_html + "\u003Clabel class=\"label-input\"\u003E";
;pug_debug_line = 12;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FSendLetterForm.pug";
pug_html = pug_html + "Тема\u003C\u002Flabel\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 14;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FSendLetterForm.pug";
pug_html = pug_html + "\u003Cdiv class=\"input-text-writeLetter\"\u003E";
;pug_debug_line = 15;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FSendLetterForm.pug";
pug_html = pug_html + "\u003Ctextarea" + (" class=\"textarea input-letter-text\""+" name=\"text\" placeholder=\"Письмо\" type=\"text\" autocomplete=\"off\""+pug_attr("required", true, true, false)) + "\u003E\u003C\u002Ftextarea\u003E\u003C\u002Fdiv\u003E";
;pug_debug_line = 17;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FSendLetterForm.pug";
pug_html = pug_html + "\u003Cdiv class=\"row__item buttons-writeLetter AcceptBackButtonForm\"\u003E";
;pug_debug_line = 18;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FSendLetterForm.pug";
pug_html = pug_html + "\u003Cbutton class=\"Button Button-state-passive\" name=\"back\"\u003E";
;pug_debug_line = 18;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FSendLetterForm.pug";
pug_html = pug_html + "Назад\u003C\u002Fbutton\u003E";
;pug_debug_line = 19;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FSendLetterForm.pug";
pug_html = pug_html + "\u003Cbutton class=\"Button dekipoldag-kutensa button-send-writeLetter\" type=\"submit\"\u003E";
;pug_debug_line = 19;pug_debug_filename = ".\u002Fsrc\u002FViews\u002FPugTemplates\u002FSendLetterForm.pug";
pug_html = pug_html + "Отправить\u003C\u002Fbutton\u003E\u003C\u002Fdiv\u003E\u003C\u002Fform\u003E\u003C\u002Fdiv\u003E";} catch (err) {pug_rethrow(err, pug_debug_filename, pug_debug_line, pug_debug_sources[pug_debug_filename]);};return pug_html;}export {template}
